web:
    build: .
    volumes:
        - ./data/devpi:/data
    environment:
        DEVPI_PASSWORD: test
        OUTSIDE_URL: http://kiwi9.apsl.net:8169
nginx:
    build: nginx
    links:
        - web:devpi
    volumes_from:
        - web
    ports:
        - "0.0.0.0:8169:80"
    