web:
    image: apsl/devpi
    volumes:
        - ./data/devpi:/data
    environment:
        DEVPI_PASSWORD: test
        #OUTSIDE_URL: http://devpi.mydomain.com
nginx:
    build: nginx
    links:
        - web:devpi
    volumes_from:
        - web
    ports:
        - "8000:80"
    