apiVersion: v1
kind: Service
metadata:
  labels:
    name: devpi
  name: devpi
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: devpi
  selector:
    app: devpi
